import React from 'react';
import Header from '../../components/Header';
import classnames from 'classnames/bind';
import Head from 'next/head';

import styles from './scholarship.module.scss';

const cx = classnames.bind(styles);

const ScholarshipPage: React.FC = () => {
    const handleApply = () => {
        window.open(
            'https://forms.gle/LzkmAykdvFYkJWuq6',
            '_blank',
            'noreferrer noopener'
        );
    };
    return (
        <div className={cx('container')}>
            <Head>
                <title>Axie Toolbox | Apply Scholarship</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <div className={cx('header-container')}>Scholarship Page</div>

            <div className={cx('content-container')}>
                <h3>Introduction</h3>
                <p>
                    Hello aspiring scholars! I am looking forward to receive
                    your application. I&apos;ve loved playing games since young and
                    always dream of being able to play and earn. In Axies
                    Infinity, and not only we can earn from it, it&apos;s a fun game
                    too! I hope this scholarship can give you the opportunity to
                    earn money and experience the fun at the same time.
                </p>

                <p>
                    We want someone who is passionate and willing to put in the
                    time to learn the games. Here are the qualities we&apos;re
                    looking for:
                </p>

                <p>
                    REQUIREMENTS:
                    <ol>
                        <li>A good communication skill in English </li>
                        <li>
                            Passionate and willing to learn to excel at the game{' '}
                        </li>
                        <li>
                            A Ronin wallet and Metamask already setup and ready
                            to receive your earnings
                        </li>
                        <li>
                            A team player and responds to communication in a
                            timely manner
                        </li>
                        <li>A device to play Axie Infinity on</li>
                    </ol>
                </p>

                <h3>TERMS AND CONDITIONS</h3>
                <p>
                    <ol>
                        <li>
                            Payout will be every 2 weeks. The payout will be in
                            SLP, payable to your own ronin wallet. Payment can
                            be done in other modes, e.g. PayNow(SG), bank
                            transfer (SG, MY), Payoneer etc. but will be
                            approved on a case by case basis. For payment mode
                            other than SLP, if there is noticable price
                            fluctuation near the cashout time, we will advise
                            further.
                        </li>
                        <li>
                            Split: Manager/Scholar: 50/50 If you earn more than
                            200 SLP per day, the split will be further increased
                            to 40/60 (Manager/Scholar). We reward you for being
                            a good player and scholar! If you refer a friend,
                            you will earn 10% of that person&apos;s earning on top of
                            your split since day 1! Once probation is over for
                            your friend, both of you get a sign up bonus of 100
                            SLP. *Do take note that you&apos;ll be responsible to
                            recommend people of good conduct, who you can voush
                            for, as if the referral violates rules and as a
                            result have to be terminated, the referee will be
                            terminated as well.
                        </li>
                        <li>
                            Minimum target: 1st week = 75 SLP / day (level up
                            and learn the games) (525 SLP / week) 2nd week = 100
                            SLP / day (600 SLP / week inclusive of 1 rest day)
                            3rd week onwards = 125 SLP / day (750 SLP / week
                            inclusive of 1 rest day)
                        </li>
                        <li>
                            {' '}
                            If target is not met: 1st time - verbal warning 2nd
                            termination Probation period: No show or
                            uncontactable for over 48 hours will result in
                            immediate termination We encouraged you to take a
                            break every now and then, because we don&apos;t want you
                            to burnt yourself out. From 2nd week onwards, you&apos;ll
                            be entitled to one day rest every week. Take a rest
                            or fight for more SLP if you feel like it! If there
                            are special situation that you are unable to play
                            for more than 1 day, please let me know and we can
                            discuss about it. If you decided not to continue
                            with the scholarship after the contract ends, a 2
                            weeks notice is required.
                        </li>
                    </ol>
                </p>

                <h3>RULES</h3>
                <p>
                    <ul>
                        <li>
                            You need to be over 18 years old and past your
                            birthday as you submit this applications
                        </li>
                        <li>Do not bot</li>
                        <li>
                            Do not multiaccount Multiaccounting is a serious
                            offence that can get the axies banned and as a
                            result, scholarship will be terminated immediately,
                            causing loss to manager, and all SLP will be
                            forfeited. The scholar will be responsible for the
                            lose incurred from banned Axies and we reserve the
                            right to
                        </li>
                    </ul>
                </p>

                <div className={cx('button-container')}>
                    <button onClick={handleApply} className="btn btn-primary">
                        Apply Now!
                    </button>
                </div>
            </div>
        </div>
    );
};

export default ScholarshipPage;
