import React from 'react';
import styles from '../../styles/Home.module.scss';
import Head from 'next/head';
import Header from '../../components/Header';
import EnergyCounter from '../../components/EnergyCounter';

const EnergyCounterPage: React.FC = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Axie Toolbox | Energy Counter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <EnergyCounter />
        </div>
    );
};

export default EnergyCounterPage;
