import type { NextPage } from 'next';
import Head from 'next/head';
import classnames from 'classnames/bind';

import Header from '../components/Header';

import styles from '../styles/Home.module.scss';
import React from "react";

const cx = classnames.bind(styles);

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Axie Toolbox | Energy Counter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6783684768888814"
                    crossOrigin="anonymous"></script>
        </div>
    );
};

export default Home;
